###########
# site.title

title: Chandradeep Pokhariya
description: 
# baseurl: "/jekyllBear" # the subpath of your site, e.g. /blog/
url: "https://coreqode.github.io" # the base hostname & protocol for your site
# host: 0.0.0.0


#########################
# more settings

plugins:
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from

markdown: kramdown

compress_html:
  clippings: all
  comments: [""]
  endings: [html, head, body, li, dt, dd, rt, rp, optgroup, option, colgroup, caption, thead, tbody, tfoot, tr, td, th]
  profile: false
  blanklines: false
  ignore:
    envs: []

# sass:
#   sass_dir: css
#   style:    compressed

collections:
  my_tags:
    output: true
    permalink: /tagged/:slug/
defaults:
  -
    scope:
      path: ""
      type: my_tags
    values:
      layout: tagged

# baseurl: ""
permalink: /blog/:slug
timezone: America/New_York
future: false

exclude:
- README.md
- LICENSE.md

exclude: [vendor]

Blog: 

# Add general links to site pages here
links:
  Publications: /publications
# Projects: /projects

# Add links for more focus here
special_links:
  CV: https://drive.google.com/file/d/1-ij27r9Xxs0XrPosQLqvPP9vjnJnNxcM/view?usp=sharing
  # "Search": https://duckduckgo.com
